use crate::api::ApiError;
use crate::transport::TransportError;
use figment::providers::{Format, Yaml};
use figment::Figment;
use reqwest::Url;
use serde::Deserialize;
use std::collections::HashMap;
use std::net::{Ipv4Addr, SocketAddr};
use std::path::PathBuf;

#[derive(Deserialize, Clone)]
pub struct Config {
    pub transport: Transport,
    pub api: ApiConfig,
}

#[derive(Deserialize, Clone)]
#[serde(tag = "type")]
pub enum Transport {
    #[serde(alias = "kafka")]
    Kafka(KafkaConfig),
    #[serde(alias = "warp10")]
    Warp10(Warp10Config),
}

#[derive(Deserialize, Clone)]
pub struct KafkaConfig {
    pub topic: String,
    pub properties: HashMap<String, String>,
}

#[derive(Deserialize, Clone)]
pub struct Warp10Config {
    /// Valid Warp10 token that is used to write results as metrics
    pub write_token: String,
    /// Warp10 service to which the broker will send metrics, in the form of `http://<host>:<port>`
    pub endpoint: Url,
    /// Specific labels that need to be added to all metrics generated by the broker
    #[serde(default)]
    pub labels: HashMap<String, String>,
    /// Allow to have an endpoint that is unsafe to use
    #[serde(default)]
    pub insecure: bool,
    /// Maximum number of check results that can be buffered before sending them to Warp10,
    /// if batch_interval is not reached
    #[serde(default = "default_batch_size")]
    pub batch_size: u64,
    /// Maximum interval to which we send a batch, if batch_size is not reached, in milliseconds
    #[serde(default = "default_batch_interval")]
    pub batch_interval: u64
}

fn default_batch_size() -> u64 {
    100
}

fn default_batch_interval() -> u64 {
    10000
}

#[derive(Deserialize, Clone)]
pub struct ApiConfig {
    pub listen_address: SocketAddr,
}

#[derive(thiserror::Error, Debug)]
pub enum Error {
    #[error("Unable to load config file: {0}")]
    UnableToLoadConfigFile(#[from] figment::Error),
    #[error("Couldn't properly start transport layer as it appears to be unavailable: {0}")]
    UnableToStartTransport(#[from] TransportError),
    #[error("Unable to start API server")]
    UnableToStartApiServer(#[from] ApiError),
}

impl Config {
    pub fn from_config_file(path: impl Into<PathBuf>) -> Result<Self, Error> {
        Ok(Figment::new().merge(Yaml::file(path.into())).extract()?)
    }
}

impl Default for Config {
    fn default() -> Self {
        Config {
            transport: Transport::Kafka(KafkaConfig {
                topic: "isok.agent.results".to_string(),
                properties: HashMap::from([(
                    "bootstrap.servers".to_string(),
                    "localhost:9092".to_string(),
                )]),
            }),
            api: ApiConfig {
                listen_address: SocketAddr::new(Ipv4Addr::LOCALHOST.into(), 9000),
            },
        }
    }
}
