[package]
name = "isok-data"
version = "0.1.0"
edition = "2024"

[features]
config = ["dep:figment"]

[dependencies]
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
schemars = { workspace = true }
http = "1.3.1"
http-serde = { workspace = true }
lazy_static = "1.5.0"
refined = { version = "0.3.1", features = ["regex"] }
figment = { workspace = true, optional = true }
prost = "0.13.5"
prost-types = "0.13.5"

[build-dependencies]
prost-build = "0.13.5"
