[package]
name = "isok-broker"
version = "0.1.0"
edition = "2024"

[dependencies]
isok-data = { workspace = true, features = ["config"] }
reqwest = { version = "0.12.9", features = ["json"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "signal"] }
serde = { version = "1.0.216", features = ["derive"] }
thiserror = { workspace = true }
figment = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
rdkafka = { version = "0.37.0", features = ["cmake-build"] }
tonic = { workspace = true }